services:
  postgres:
    image: postgres:15-alpine
    container_name: home360-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  mongo:
    image: mongo
    container_name: home360-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - db:/data/db

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: home360-rabbitmq
    ports:
      - "5672:5672" # Standard AMQP port
      - "61613:61613" # STOMP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Enable the STOMP plugin
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
      

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - mongo
      - redis
      - rabbitmq
    restart: on-failure
    container_name: home360-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file: .env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
#    links:
#      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_APPLICATION_JSON: '{
                   "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
                   "spring.datasource.username" : "$POSTGRES_USER",
                   "spring.datasource.password" : "$POSTGRES_PASSWORD",
                   "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
                   "spring.jpa.hibernate.ddl-auto" : "create-drop"
                 }'

    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

volumes:
  redis_data:
    driver: local
  db: