version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: home360-server
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
      SPRING_APPLICATION_JSON: |
        {
                 "spring.datasource.url"  : "${PROD_POSTGRES_DATABASE_URL}",
                 "spring.datasource.username" : "{$PROD_POSTGRES_USER}",
                 "spring.datasource.password" : "{$PROD_POSTGRES_PASSWORD}",
                 "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
                 "spring.jpa.hibernate.ddl-auto" : "update"
        }

    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2