server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      database: home360dev
      auto-index-creation: true
      uri: mongodb://localhost:27017/home360dev
      embedded:
        enabled: false

  output:
    ansi:
      enabled: DETECT
  datasource:
    url: jdbc:postgresql://localhost:5432/home360_dev
    username: hoxtygen
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database: postgresql
    show-sql: true
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: 4125442A472D4B6150645367566B58703273357638792F423F4528482B4D6251655468576D5A7133743677397A24432646294A404E635266556A586E32723575
      jwtTokenExpirationMs: 86400000

logging:
  file.name: logs/application-debug.log
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.codeplanks: DEBUG
    org.hibernate: ERROR