server:
  port: <port>

spring:
  config:
    activate:
      on-profiles: dev

  mail:
    host: <enter host>
    port: <enter port>
    username: <enter username>
    password: <enter password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      host: localhost
      authentication-database: <authentication database name>
      database: <enter database name>
      auto-index-creation: true
      uri: mongodb://localhost:27017/<database name>
      embedded:
        enabled: false

  output:
    ansi:
      enabled: DETECT
  datasource:
    url: jdbc:postgresql://localhost:<port>/<database name>
    username: <enter database username>
    password: <enter database password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database: postgresql
    show-sql: true
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: <jwt secret key>
      jwtTokenExpirationMs: <jwt expiration time>

  frontend:
    url: <frontend base url>
    password-reset-request:
      url: <frontend password reset request url>
    reset-password:
      url: <frontend password reset url>
    verify-email:
      url: <frontend email verification page>

logging:
  file.name: <log file url>
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.codeplanks: DEBUG
    org.hibernate: ERROR