server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/home360_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database: postgresql
    show-sql: true
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: 4125442A472D4B6150645367566B58703273357638792F423F4528482B4D6251655468576D5A7133743677397A24432646294A404E635266556A586E32723575