server:
  port: <port>

spring:
  application:
    name: Home360
  config:
    activate:
      on-profile: dev

  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000

  mail:
    host: <enter host>
    port: <enter port>
    username: <enter username>
    password: <enter password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      authentication-database: admin
      database: home360dev
      auto-index-creation: true
      uri: mongodb://localhost:27017/home360dev
      embedded:
        enabled: false

  output:
    ansi:
      enabled: DETECT
  datasource:
    url: jdbc:postgresql://localhost:<port>/<database name>
    username: <enter database username>
    password: <enter database password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database: postgresql
    show-sql: true
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: <jwt secret key>
      jwtTokenExpirationMs: <jwt expiration time>

  frontend:
    url: <frontend base url>
    password-reset-request:
      url: <frontend password reset request url>
    reset-password:
      url: <frontend password reset url>
    verify-email:
      url: <frontend email verification page>
    user-listings-url:
      url: <frontend listing url>

  mail:
    mailSenderName: Home360
    mailSenderAddress: udubit@hotmail.com

logging:
  file.name: <log file url>
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.codeplanks: DEBUG
    org.hibernate: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.orm: DEBUG
    org.springframework.cache: DEBUG
    
management:
  info:
    git:
      mode: full
    env:
      enabled: true
    java:
      enabled: true
  app:
    name: Home360
    description: "Home360 Application"
    version: 1.0.0
  env:
    enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    db:
      enabled: true
    redis:
      enabled: true
    metrics:
      enabled: true
      prometheus:
        enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: ${spring.application.name}
    description: Application for real estate agents
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'