spring:
  profiles: test

  data:
    mongodb:
      embedded:
        version: "5.0.5"
        enabled: true
      database: home360test
      port: 27018
de.flapdoodle.mongodb.embedded.version: 6.0.5

